version: '3.8'

services:
  news-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-ai-agent
    ports:
      - "${PORT:-8000}"
    networks:
      - synz
    volumes:
      # Mount .env file for configuration
      - ./.env:/app/.env:ro
    environment:
      # Add any environment variables here if needed
      - MODEL_CHOICE=${MODEL_CHOICE}
      - BASE_URL=${BASE_URL}
      - LLM_API_KEY=${LLM_API_KEY}
      - BRAVE_SSE_URL=${BRAVE_SSE_URL}
      - GHOST_SSE_URL=${GHOST_SSE_URL}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
    restart: unless-stopped

networks:
  synz:
    external: true